version: '3'

services:
  web:
    build: .
    command: npm start
    image: randomlylostperson/sellerinfo:latest
    ports:
      - "7770:7770"
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: postgres://colemichaels@db:5432/frontend_capstone

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: colemichaels
      POSTGRES_DB: frontend_capstone